/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/onload.gltf --transform 
Files: public/onload.gltf [13.86MB] > /home/shad/PycharmProjects/javascrypt/nodejs/maintenance_site_project/onload-transformed.glb [3.53MB] (75%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/onload-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AP727101290_Default<As_Machined>'].geometry} material={materials.PaletteMaterial001} position={[0.55, 1.047, -0.252]} rotation={[0, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/onload-transformed.glb')
