/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ConvCarrier_R.gltf --transform -o src/ConvCarrier_R.jsx 
Files: public/ConvCarrier_R.gltf [2.07MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/ConvCarrier_R-transformed.glb [345.96KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConvCarrier_R({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/ConvCarrier_R-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727515001.geometry} material={materials.PaletteMaterial001} position={[-0.427, 0.871, -0.992]} rotation={[0, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/ConvCarrier_R-transformed.glb')
