/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Conv_L.gltf --transform -o src/Conv_L.jsx 
Files: public/Conv_L.gltf [430.09KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/Conv_L-transformed.glb [48.26KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Conv_L({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/Conv_L-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727515549.geometry} material={materials.mat_0} position={[0.4, 1.32, -1.119]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Conv_L-transformed.glb')
