/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Conv_static.gltf --transform -o src/Conv_static.jsx 
Files: public/Conv_static.gltf [1.4MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/Conv_static-transformed.glb [139.68KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Conv_static({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/Conv_static-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727515522.geometry} material={materials.mat_0} position={[0, 1.14, -0.51]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh userData={{hoverId}} geometry={nodes.AP126116733_Full_Detail028.geometry} material={materials.mat_1} position={[-0.385, 0.17, 0]} />
      <mesh userData={{hoverId}} geometry={nodes.AP727514879.geometry} material={materials.mat_2} position={[0, 1.145, -0.51]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Conv_static-transformed.glb')
