/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ValveTerminal.gltf --transform -o src/ValveTerminal.jsx 
Files: public/ValveTerminal.gltf [1.06MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/ValveTerminal-transformed.glb [235.78KB] (78%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function VTerminal({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/ValveTerminal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727515364.geometry} material={materials.PaletteMaterial001} position={[0.433, 0.369, -0.332]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/models/ValveTerminal-transformed.glb')
