/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Carrier_V.gltf --transform -o src/Carrier_V.jsx 
Files: public/Carrier_V.gltf [6.1MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/Carrier_V-transformed.glb [1.1MB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Carrier_Vertical({hoverId, ...props }) {
  const { nodes, materials } = useGLTF('/models/Carrier_V-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP226222024_91202A267.geometry} material={materials.PaletteMaterial001} position={[0.202, 0.98, -0.313]} rotation={[3.022, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/models/Carrier_V-transformed.glb')
