/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Conv_R.gltf --transform -o src/Conv_R.jsx 
Files: public/Conv_R.gltf [433.06KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/Conv_R-transformed.glb [42.4KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Conv_R({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/Conv_R-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727515534.geometry} material={materials.mat_0} position={[-0.4, 1.32, -1.119]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Conv_R-transformed.glb')
