/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ConvCarrier_L.gltf --transform -o src/ConvCarrier_L.jsx 
Files: public/ConvCarrier_L.gltf [2.07MB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/ConvCarrier_L-transformed.glb [307.27KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConvCarrier({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/ConvCarrier_L-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727514869.geometry} material={materials.PaletteMaterial001} position={[0.427, 0.233, -0.992]} />
    </group>
  )
}

useGLTF.preload('/models/ConvCarrier_L-transformed.glb')
