/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/EnergoChain.gltf --transform -o src/EnergoChain.jsx 
Files: public/EnergoChain.gltf [978.62KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/EnergoChain-transformed.glb [70.32KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EnChain({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/EnergoChain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AP727515253.geometry} material={materials.mat_0} position={[0.263, 0.767, -0.35]} rotation={[-Math.PI, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.AP727515255.geometry} material={materials.mat_1} position={[0.276, 0.767, -0.35]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/EnergoChain-transformed.glb')
