/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/LoadStationFrame.gltf --transform -o src/LoadStationFrame.jsx 
Files: public/LoadStationFrame.gltf [902.07KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/LoadStationFrame-transformed.glb [212.83KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LoadStFrame({hoverId, ...props}) {

//   function handlePointerOver(e) {
//   e.stopPropagation();
//   if (mouseOn) mouseOn();
//   console.log("Hovered")
// }

// function handlePointerOut(e) {
//   e.stopPropagation();
//   if(mouseOff) mouseOff();
// }


  const { nodes, materials } = useGLTF('/models/LoadStationFrame-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AP727101290_Default<As_Machined>024'].geometry} 
            material={materials.PaletteMaterial001} 
            position={[0.55, 1.047, -0.252]} 
            rotation={[0, 0, -Math.PI]}
            userData={{hoverId}}
            />
    </group>
  )
}

useGLTF.preload('/models/LoadStationFrame-transformed.glb')
