/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/PilotValve.gltf --transform -o src/PilotValve.jsx 
Files: public/PilotValve.gltf [610.41KB] > /home/shad/PycharmProjects/javascrypt/nodejs/project_maintenance/src/PilotValve-transformed.glb [179.84KB] (71%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PilotV({hoverId, ...props}) {
  const { nodes, materials } = useGLTF('/models/PilotValve-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh userData={{hoverId}} geometry={nodes.AP727515426.geometry} material={materials.PaletteMaterial001} position={[0.417, 0.827, -0.351]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/models/PilotValve-transformed.glb')
